# Generated by Django 5.0.2 on 2024-02-29 17:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=datetime.datetime(2024, 2, 29, 17, 10, 39, 390838, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа')),
                ('payment_amount', models.FloatField(verbose_name='Сумма платежа')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Безналичная оплата')], default='cash', max_length=20, verbose_name='Способ платежа')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paid', to='materials.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paid', to='materials.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-payment_date',),
            },
        ),
    ]
