# Generated by Django 5.0.2 on 2024-03-06 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 12, 27, 48, 371356, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
    ]
