# Generated by Django 5.0.1 on 2024-03-20 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 9, 5, 39, 354880, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
    ]
