# Generated by Django 5.0.1 on 2024-04-07 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 8, 7, 8, 546002, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
    ]
